// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.1.34438 Microsoft Reciprocal License (Ms-RL) 
//    <NameSpace>StefanOlsen.Commerce.CatalogFeed.Mapping</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace StefanOlsen.Commerce.CatalogFeed.Mapping
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "complexType.FixedFieldType", Namespace = "http://stefanolsen.com/CatalogFeed.GoogleMerchant/MappingDocument.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("FixedField", Namespace = "http://stefanolsen.com/CatalogFeed.GoogleMerchant/MappingDocument.xsd", IsNullable = false)]
    public partial class complexTypeFixedFieldType : complexTypeBaseFieldType
    {

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value { get; set; }

    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(complexTypeFixedFieldType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(complexTypeMappedFieldType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "complexType.BaseFieldType", Namespace = "http://stefanolsen.com/CatalogFeed.GoogleMerchant/MappingDocument.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("complexType.BaseFieldType", Namespace = "http://stefanolsen.com/CatalogFeed.GoogleMerchant/MappingDocument.xsd", IsNullable = true)]
    public abstract partial class complexTypeBaseFieldType
    {

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FeedField { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "complexType.MappedFieldType", Namespace = "http://stefanolsen.com/CatalogFeed.GoogleMerchant/MappingDocument.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("MappedField", Namespace = "http://stefanolsen.com/CatalogFeed.GoogleMerchant/MappingDocument.xsd", IsNullable = false)]
    public partial class complexTypeMappedFieldType : complexTypeBaseFieldType
    {

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MetaField { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://stefanolsen.com/CatalogFeed.GoogleMerchant/MappingDocument.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://stefanolsen.com/CatalogFeed.GoogleMerchant/MappingDocument.xsd", IsNullable = false)]
    public partial class FieldMapping
    {

        private complexTypeContentType[] contentTypeField;

        [System.Xml.Serialization.XmlElementAttribute("ContentType")]
        public complexTypeContentType[] ContentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "complexType.ContentType", Namespace = "http://stefanolsen.com/CatalogFeed.GoogleMerchant/MappingDocument.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("complexType.ContentType", Namespace = "http://stefanolsen.com/CatalogFeed.GoogleMerchant/MappingDocument.xsd", IsNullable = true)]
    public partial class complexTypeContentType
    {

        private complexTypeBaseFieldType[] fieldsField;

        public complexTypeImageGroup ImageGroup { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public simpleTypeCommerceEntityType CommerceType { get; set; }


        [System.Xml.Serialization.XmlArrayItemAttribute("FixedField", typeof(complexTypeFixedFieldType), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MappedField", typeof(complexTypeMappedFieldType), IsNullable = false)]
        public complexTypeBaseFieldType[] Fields
        {
            get
            {
                return this.fieldsField;
            }
            set
            {
                this.fieldsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "complexType.ImageGroup", Namespace = "http://stefanolsen.com/CatalogFeed.GoogleMerchant/MappingDocument.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("complexType.ImageGroup", Namespace = "http://stefanolsen.com/CatalogFeed.GoogleMerchant/MappingDocument.xsd", IsNullable = true)]
    public partial class complexTypeImageGroup
    {

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AssetMetaField { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "simpleType.CommerceEntityType", Namespace = "http://stefanolsen.com/CatalogFeed.GoogleMerchant/MappingDocument.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("simpleType.CommerceEntityType", Namespace = "http://stefanolsen.com/CatalogFeed.GoogleMerchant/MappingDocument.xsd", IsNullable = false)]
    public enum simpleTypeCommerceEntityType
    {

        /// <remarks/>
        CatalogNode,

        /// <remarks/>
        Product,

        /// <remarks/>
        Variation,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "complexType.FieldsType", Namespace = "http://stefanolsen.com/CatalogFeed.GoogleMerchant/MappingDocument.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("complexType.FieldsType", Namespace = "http://stefanolsen.com/CatalogFeed.GoogleMerchant/MappingDocument.xsd", IsNullable = true)]
    public partial class complexTypeFieldsType
    {

        private complexTypeBaseFieldType[] itemsField;

        [System.Xml.Serialization.XmlElementAttribute("FixedField", typeof(complexTypeFixedFieldType))]
        [System.Xml.Serialization.XmlElementAttribute("MappedField", typeof(complexTypeMappedFieldType))]
        public complexTypeBaseFieldType[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
}
